import 'package:flutter/material.dart';
import '../../../gen/fonts.gen.dart';

TextTheme taskTextTheme() {
  return const TextTheme(
    displayLarge: TextStyle(
      fontFamily: FontFamily.tryClother,
      fontSize: 57,
      fontStyle: FontStyle.normal,
      fontWeight: FontWeight.w500,
      // letterSpacing: -0.25,
      // height: 64 / 57,
    ),
    displayMedium: TextStyle(
      fontFamily: FontFamily.tryClother,
      fontSize: 45,
      fontStyle: FontStyle.normal,
      fontWeight: FontWeight.w500,
      // height: 52 / 45,
    ),
    displaySmall: TextStyle(
      fontFamily: FontFamily.tryClother,
      fontSize: 36,
      fontStyle: FontStyle.normal,
      fontWeight: FontWeight.w500,
      // height: 44 / 36,
    ),
    headlineLarge: TextStyle(
      fontFamily: FontFamily.tryClother,
      fontSize: 32,
      fontStyle: FontStyle.normal,
      fontWeight: FontWeight.w500,
      // height: 40 / 32,
    ),
    headlineMedium: TextStyle(
      fontFamily: FontFamily.tryClother,
      fontSize: 28,
      fontStyle: FontStyle.normal,
      fontWeight: FontWeight.w700,
      // height: 36 / 28,
    ),
    headlineSmall: TextStyle(
      fontFamily: FontFamily.tryClother,
      fontSize: 24,
      fontStyle: FontStyle.normal,
      fontWeight: FontWeight.w700,
      // height: 32 / 24,
    ),
    titleLarge: TextStyle(
      fontFamily: FontFamily.tryClother,
      fontSize: 22,
      // fontStyle: FontStyle.normal,
      fontWeight: FontWeight.w500,
      // height: 28 / 22,
    ),
    titleMedium: TextStyle(
      fontFamily: FontFamily.tryClother,
      fontSize: 16,
      fontStyle: FontStyle.normal,
      fontWeight: FontWeight.w500,
      // height: 24 / 16,
      // letterSpacing: 0.15,
    ),
    titleSmall: TextStyle(
      fontFamily: FontFamily.tryClother,
      fontSize: 14,
      fontStyle: FontStyle.normal,
      fontWeight: FontWeight.w500,
      // height: 20 / 14,
      // letterSpacing: 0.1,
    ),
    bodyLarge: TextStyle(
      fontFamily: FontFamily.tryClother,
      fontSize: 16,
      fontStyle: FontStyle.normal,
      fontWeight: FontWeight.w500,
      // height: 24 / 16,
      // letterSpacing: 0.5,
    ),
    bodyMedium: TextStyle(
      fontFamily: FontFamily.tryClother,
      fontSize: 14,
      fontStyle: FontStyle.normal,
      fontWeight: FontWeight.w400,
      // height: 20 / 14,
      // letterSpacing: 0.25,
    ),
    bodySmall: TextStyle(
      fontFamily: FontFamily.tryClother,
      fontSize: 12,
      fontStyle: FontStyle.normal,
      fontWeight: FontWeight.w400,
      // height: 16 / 12,
      // letterSpacing: 0.4,
    ),
    labelLarge: TextStyle(
      fontFamily: FontFamily.tryClother,
      fontSize: 14,
      fontStyle: FontStyle.normal,
      fontWeight: FontWeight.w500,
      // height: 20 / 14,
      // letterSpacing: 0.1,
    ),
    labelMedium: TextStyle(
      fontFamily: FontFamily.tryClother,
      fontSize: 12,
      fontStyle: FontStyle.normal,
      fontWeight: FontWeight.w500,
      // height: 16 / 12,
      // letterSpacing: 0.5,
    ),
    labelSmall: TextStyle(
      fontFamily: FontFamily.tryClother,
      fontSize: 11,
      fontStyle: FontStyle.normal,
      fontWeight: FontWeight.w500,
      // height: 16 / 11,
      // letterSpacing: 0.5,
    ),
  );
}
